// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 10 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encoderstatus_10 = 10;
	/// <summary>PID: 10 | Type: read</summary>
	public const int encoderstatus = 10;
	/// <summary>PID: 13 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encodercurrentcompressedbitrate_13 = 13;
	/// <summary>PID: 13 | Type: read</summary>
	public const int encodercurrentcompressedbitrate = 13;
	/// <summary>PID: 14 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encoderautochromaweight_14 = 14;
	/// <summary>PID: 14 | Type: read</summary>
	public const int encoderautochromaweight = 14;
	/// <summary>PID: 15 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int chromaweight_15 = 15;
	/// <summary>PID: 15 | Type: read</summary>
	public const int chromaweight = 15;
	/// <summary>PID: 16 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int losslessmode_16 = 16;
	/// <summary>PID: 16 | Type: read</summary>
	public const int losslessmode = 16;
	/// <summary>PID: 20 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decoderstatus_20 = 20;
	/// <summary>PID: 20 | Type: read</summary>
	public const int decoderstatus = 20;
	/// <summary>PID: 21 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decodercurrentcompressedbitrate_21 = 21;
	/// <summary>PID: 21 | Type: read</summary>
	public const int decodercurrentcompressedbitrate = 21;
	/// <summary>PID: 22 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int progressionorder_22 = 22;
	/// <summary>PID: 22 | Type: read</summary>
	public const int progressionorder = 22;
	/// <summary>PID: 23 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int codeblockwidth_23 = 23;
	/// <summary>PID: 23 | Type: read</summary>
	public const int codeblockwidth = 23;
	/// <summary>PID: 24 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int codeblockheight_24 = 24;
	/// <summary>PID: 24 | Type: read</summary>
	public const int codeblockheight = 24;
	/// <summary>PID: 25 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encodercurrentcompressedbitratedummy_25 = 25;
	/// <summary>PID: 25 | Type: read</summary>
	public const int encodercurrentcompressedbitratedummy = 25;
	/// <summary>PID: 26 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encoderautochromaweightdummy_26 = 26;
	/// <summary>PID: 26 | Type: read</summary>
	public const int encoderautochromaweightdummy = 26;
	/// <summary>PID: 27 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int chromaweightdummy_27 = 27;
	/// <summary>PID: 27 | Type: read</summary>
	public const int chromaweightdummy = 27;
	/// <summary>PID: 28 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int losslessmodedummy_28 = 28;
	/// <summary>PID: 28 | Type: read</summary>
	public const int losslessmodedummy = 28;
	/// <summary>PID: 29 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decodercurrentcompressedbitratedummy_29 = 29;
	/// <summary>PID: 29 | Type: read</summary>
	public const int decodercurrentcompressedbitratedummy = 29;
	/// <summary>PID: 30 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int progressionorderdummy_30 = 30;
	/// <summary>PID: 30 | Type: read</summary>
	public const int progressionorderdummy = 30;
	/// <summary>PID: 31 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int codeblockwidthdummy_31 = 31;
	/// <summary>PID: 31 | Type: read</summary>
	public const int codeblockwidthdummy = 31;
	/// <summary>PID: 32 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int codeblockheightdummy_32 = 32;
	/// <summary>PID: 32 | Type: read</summary>
	public const int codeblockheightdummy = 32;
	/// <summary>PID: 34 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int fixedzero_34 = 34;
	/// <summary>PID: 34 | Type: read</summary>
	public const int fixedzero = 34;
	public class Write
	{
		/// <summary>PID: 60 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int encoderstatus_60 = 60;
		/// <summary>PID: 60 | Type: write</summary>
		public const int encoderstatus = 60;
		/// <summary>PID: 64 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int encoderautochromaweight_64 = 64;
		/// <summary>PID: 64 | Type: write</summary>
		public const int encoderautochromaweight = 64;
		/// <summary>PID: 65 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int chromaweight_65 = 65;
		/// <summary>PID: 65 | Type: write</summary>
		public const int chromaweight = 65;
		/// <summary>PID: 66 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int losslessmode_66 = 66;
		/// <summary>PID: 66 | Type: write</summary>
		public const int losslessmode = 66;
		/// <summary>PID: 70 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int decoderstatus_70 = 70;
		/// <summary>PID: 70 | Type: write</summary>
		public const int decoderstatus = 70;
		/// <summary>PID: 72 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int progressionorder_72 = 72;
		/// <summary>PID: 72 | Type: write</summary>
		public const int progressionorder = 72;
	}
}
public class WriteParameters
{
	/// <summary>PID: 60  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Encoderstatus {get { return Protocol.GetParameter(60); }set { Protocol.SetParameter(60, value); }}
	/// <summary>PID: 64  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Encoderautochromaweight {get { return Protocol.GetParameter(64); }set { Protocol.SetParameter(64, value); }}
	/// <summary>PID: 65  | Type: write</summary>
	public System.Object Chromaweight {get { return Protocol.GetParameter(65); }set { Protocol.SetParameter(65, value); }}
	/// <summary>PID: 66  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Losslessmode {get { return Protocol.GetParameter(66); }set { Protocol.SetParameter(66, value); }}
	/// <summary>PID: 70  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Decoderstatus {get { return Protocol.GetParameter(70); }set { Protocol.SetParameter(70, value); }}
	/// <summary>PID: 72  | Type: write | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4</summary>
	public System.Object Progressionorder {get { return Protocol.GetParameter(72); }set { Protocol.SetParameter(72, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	object Afterstartup_dummy { get; set; }
	object Fixedminusone__fixed { get; set; }
	object Encoderstatus_10 { get; set; }
	object Encoderstatus { get; set; }
	object Encodertitlebegin__fixed { get; set; }
	object Encodertitleend__fixed { get; set; }
	object Encodercurrentcompressedbitrate_13 { get; set; }
	object Encodercurrentcompressedbitrate { get; set; }
	object Encoderautochromaweight_14 { get; set; }
	object Encoderautochromaweight { get; set; }
	object Chromaweight_15 { get; set; }
	object Chromaweight { get; set; }
	object Losslessmode_16 { get; set; }
	object Losslessmode { get; set; }
	object Decodertitlebegin__fixed { get; set; }
	object Decodertitleend__fixed { get; set; }
	object Decoderstatus_20 { get; set; }
	object Decoderstatus { get; set; }
	object Decodercurrentcompressedbitrate_21 { get; set; }
	object Decodercurrentcompressedbitrate { get; set; }
	object Progressionorder_22 { get; set; }
	object Progressionorder { get; set; }
	object Codeblockwidth_23 { get; set; }
	object Codeblockwidth { get; set; }
	object Codeblockheight_24 { get; set; }
	object Codeblockheight { get; set; }
	object Encodercurrentcompressedbitratedummy_25 { get; set; }
	object Encodercurrentcompressedbitratedummy { get; set; }
	object Encoderautochromaweightdummy_26 { get; set; }
	object Encoderautochromaweightdummy { get; set; }
	object Chromaweightdummy_27 { get; set; }
	object Chromaweightdummy { get; set; }
	object Losslessmodedummy_28 { get; set; }
	object Losslessmodedummy { get; set; }
	object Decodercurrentcompressedbitratedummy_29 { get; set; }
	object Decodercurrentcompressedbitratedummy { get; set; }
	object Progressionorderdummy_30 { get; set; }
	object Progressionorderdummy { get; set; }
	object Codeblockwidthdummy_31 { get; set; }
	object Codeblockwidthdummy { get; set; }
	object Codeblockheightdummy_32 { get; set; }
	object Codeblockheightdummy { get; set; }
	object Fixedone__fixed { get; set; }
	object Fixedzero_34 { get; set; }
	object Fixedzero { get; set; }
	object Encoderstatus_60 { get; set; }
	object Encoderautochromaweight_64 { get; set; }
	object Chromaweight_65 { get; set; }
	object Losslessmode_66 { get; set; }
	object Decoderstatus_70 { get; set; }
	object Progressionorder_72 { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 2  | Type: dummy</summary>
	public System.Object Afterstartup_dummy {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 5  | Type: fixed</summary>
	public System.Object Fixedminusone__fixed {get { return GetParameter(5); }set { SetParameter(5, value); }}
	/// <summary>PID: 10  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderstatus_10 {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 10  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Encoderstatus {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 11  | Type: fixed</summary>
	public System.Object Encodertitlebegin__fixed {get { return GetParameter(11); }set { SetParameter(11, value); }}
	/// <summary>PID: 12  | Type: fixed</summary>
	public System.Object Encodertitleend__fixed {get { return GetParameter(12); }set { SetParameter(12, value); }}
	/// <summary>PID: 13  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encodercurrentcompressedbitrate_13 {get { return GetParameter(13); }set { SetParameter(13, value); }}
	/// <summary>PID: 13  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Encodercurrentcompressedbitrate {get { return GetParameter(13); }set { SetParameter(13, value); }}
	/// <summary>PID: 14  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderautochromaweight_14 {get { return GetParameter(14); }set { SetParameter(14, value); }}
	/// <summary>PID: 14  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Encoderautochromaweight {get { return GetParameter(14); }set { SetParameter(14, value); }}
	/// <summary>PID: 15  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Chromaweight_15 {get { return GetParameter(15); }set { SetParameter(15, value); }}
	/// <summary>PID: 15  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Chromaweight {get { return GetParameter(15); }set { SetParameter(15, value); }}
	/// <summary>PID: 16  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Losslessmode_16 {get { return GetParameter(16); }set { SetParameter(16, value); }}
	/// <summary>PID: 16  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Losslessmode {get { return GetParameter(16); }set { SetParameter(16, value); }}
	/// <summary>PID: 18  | Type: fixed</summary>
	public System.Object Decodertitlebegin__fixed {get { return GetParameter(18); }set { SetParameter(18, value); }}
	/// <summary>PID: 19  | Type: fixed</summary>
	public System.Object Decodertitleend__fixed {get { return GetParameter(19); }set { SetParameter(19, value); }}
	/// <summary>PID: 20  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decoderstatus_20 {get { return GetParameter(20); }set { SetParameter(20, value); }}
	/// <summary>PID: 20  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Decoderstatus {get { return GetParameter(20); }set { SetParameter(20, value); }}
	/// <summary>PID: 21  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decodercurrentcompressedbitrate_21 {get { return GetParameter(21); }set { SetParameter(21, value); }}
	/// <summary>PID: 21  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Decodercurrentcompressedbitrate {get { return GetParameter(21); }set { SetParameter(21, value); }}
	/// <summary>PID: 22  | Type: read | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4 | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Progressionorder_22 {get { return GetParameter(22); }set { SetParameter(22, value); }}
	/// <summary>PID: 22  | Type: read | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4 | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Progressionorder {get { return GetParameter(22); }set { SetParameter(22, value); }}
	/// <summary>PID: 23  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Codeblockwidth_23 {get { return GetParameter(23); }set { SetParameter(23, value); }}
	/// <summary>PID: 23  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Codeblockwidth {get { return GetParameter(23); }set { SetParameter(23, value); }}
	/// <summary>PID: 24  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Codeblockheight_24 {get { return GetParameter(24); }set { SetParameter(24, value); }}
	/// <summary>PID: 24  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Codeblockheight {get { return GetParameter(24); }set { SetParameter(24, value); }}
	/// <summary>PID: 25  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encodercurrentcompressedbitratedummy_25 {get { return GetParameter(25); }set { SetParameter(25, value); }}
	/// <summary>PID: 25  | Type: read</summary>
	public System.Object Encodercurrentcompressedbitratedummy {get { return GetParameter(25); }set { SetParameter(25, value); }}
	/// <summary>PID: 26  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderautochromaweightdummy_26 {get { return GetParameter(26); }set { SetParameter(26, value); }}
	/// <summary>PID: 26  | Type: read</summary>
	public System.Object Encoderautochromaweightdummy {get { return GetParameter(26); }set { SetParameter(26, value); }}
	/// <summary>PID: 27  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Chromaweightdummy_27 {get { return GetParameter(27); }set { SetParameter(27, value); }}
	/// <summary>PID: 27  | Type: read</summary>
	public System.Object Chromaweightdummy {get { return GetParameter(27); }set { SetParameter(27, value); }}
	/// <summary>PID: 28  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Losslessmodedummy_28 {get { return GetParameter(28); }set { SetParameter(28, value); }}
	/// <summary>PID: 28  | Type: read</summary>
	public System.Object Losslessmodedummy {get { return GetParameter(28); }set { SetParameter(28, value); }}
	/// <summary>PID: 29  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decodercurrentcompressedbitratedummy_29 {get { return GetParameter(29); }set { SetParameter(29, value); }}
	/// <summary>PID: 29  | Type: read</summary>
	public System.Object Decodercurrentcompressedbitratedummy {get { return GetParameter(29); }set { SetParameter(29, value); }}
	/// <summary>PID: 30  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Progressionorderdummy_30 {get { return GetParameter(30); }set { SetParameter(30, value); }}
	/// <summary>PID: 30  | Type: read</summary>
	public System.Object Progressionorderdummy {get { return GetParameter(30); }set { SetParameter(30, value); }}
	/// <summary>PID: 31  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Codeblockwidthdummy_31 {get { return GetParameter(31); }set { SetParameter(31, value); }}
	/// <summary>PID: 31  | Type: read</summary>
	public System.Object Codeblockwidthdummy {get { return GetParameter(31); }set { SetParameter(31, value); }}
	/// <summary>PID: 32  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Codeblockheightdummy_32 {get { return GetParameter(32); }set { SetParameter(32, value); }}
	/// <summary>PID: 32  | Type: read</summary>
	public System.Object Codeblockheightdummy {get { return GetParameter(32); }set { SetParameter(32, value); }}
	/// <summary>PID: 33  | Type: fixed</summary>
	public System.Object Fixedone__fixed {get { return GetParameter(33); }set { SetParameter(33, value); }}
	/// <summary>PID: 34  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Fixedzero_34 {get { return GetParameter(34); }set { SetParameter(34, value); }}
	/// <summary>PID: 34  | Type: read</summary>
	public System.Object Fixedzero {get { return GetParameter(34); }set { SetParameter(34, value); }}
	/// <summary>PID: 60  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderstatus_60 {get { return GetParameter(60); }set { SetParameter(60, value); }}
	/// <summary>PID: 64  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderautochromaweight_64 {get { return GetParameter(64); }set { SetParameter(64, value); }}
	/// <summary>PID: 65  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Chromaweight_65 {get { return GetParameter(65); }set { SetParameter(65, value); }}
	/// <summary>PID: 66  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Losslessmode_66 {get { return GetParameter(66); }set { SetParameter(66, value); }}
	/// <summary>PID: 70  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decoderstatus_70 {get { return GetParameter(70); }set { SetParameter(70, value); }}
	/// <summary>PID: 72  | Type: write | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Progressionorder_72 {get { return GetParameter(72); }set { SetParameter(72, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		Write = new WriteParameters(this);
	}
}
}
